INITIAL_SPEED = 50
INITIAL_SPAWN_RATE = 3
INITIAL_ENEMIES = 3

SPEED_INCREMENT = 5
SPAWN_RATE_DECREMENT = 0.2
ENEMIES_INCREMENT = 0.5

SPEED_LIMIT = 200
SPAWN_RATE_LIMIT = 1
ENEMIES_LIMIT = 20

POINTS_PER_ENEMY = 10
SPRITES_SCALING = 0.4
BGM_VOLUME = 0.5
SFX_VOLUME = 0.5

TANK_SPAWN_MARGIN = 20