IMAGE_SCALING = 1
BASE_SIZE = 32 * IMAGE_SCALING

WALK_SPEED = 64 * IMAGE_SCALING
WALK_ANIMATION_INTERVAL = 0.2
WALK_DISTANCE = BASE_SIZE
BORDER_DISTANCE = BASE_SIZE

WORD_RENDERING_SPEED = 0.02

BGM_VOLUME = 0.5
SFX_VOLUME = 0.5

-- debug parameters
DRAW_HITBOX = true